apache/trafficserver-ci

docker/docs/Dockerfile, docker/docs/docker-compose.yml
initial commit of some test docker files, these will probably change
=> Add docker files for docs build

jenkins/fedora.pipeline, jenkins/ubuntu.pipeline
Adding jenkins files for builds
=> Adding ubutnu and fedora pipeline builds

docker/ubuntu/Dockerfile
this should include all necessary build tools, libs, as well as clang since ubuntu gets used for both types of builds
=> Adding dockerfile for the ubuntu image for building

jenkins/branch/autest.pipeline, jenkins/branch/branch_build.pipeline, jenkins/branch/clang_analyzer.pipeline, jenkins/branch/clang_format.pipeline, jenkins/branch/distro_builds.pipeline, jenkins/branch/in_tree.pipeline, jenkins/branch/os_build.pipeline, jenkins/branch/out_of_tree.pipeline, jenkins/branch/rat.pipeline
jenkins/branch/*.pipeline scripts
=> add initial branch build pipelines

jenkins/bin/autest.sh, jenkins/bin/build.sh, jenkins/bin/cache-tests.sh, jenkins/bin/clang-analyzer.sh, jenkins/bin/clang-format.sh, jenkins/bin/cleanup.sh, jenkins/bin/coverity.sh, jenkins/bin/docs.sh, jenkins/bin/environment.sh, jenkins/bin/extract.sh, jenkins/bin/gh-mirror.sh, jenkins/bin/github.sh, jenkins/bin/in_tree.sh, jenkins/bin/out_of_tree.sh, jenkins/bin/rat.sh, jenkins/bin/regression.sh, jenkins/bin/snapshot.sh
needed shell scripts for jenkins branch pipelines.
=> add initial jenkins scripts

jenkins/branch/clang_analyzer.pipeline, jenkins/branch/clang_format.pipeline, jenkins/branch/in_tree.pipeline, jenkins/branch/out_of_tree.pipeline, jenkins/branch/rat.pipeline
Moves from old fedora and doc containers to centos 8 container.
=> change utility pipelines to use centos8 container

jenkins/branch/coverage.pipeline
This is used to generate a coverage report for our set of various
automated tests (unit, regression, AuTest).
=> Adding a coverage.pipeline script.

jenkins/branch/autest.pipeline, jenkins/branch/clang_analyzer.pipeline, jenkins/branch/clang_format.pipeline, jenkins/branch/coverage.pipeline, jenkins/branch/in_tree.pipeline, jenkins/branch/os_build.pipeline, jenkins/branch/out_of_tree.pipeline, jenkins/branch/rat.pipeline
attempt to fix branch build failures from git clone of mirror
=> branch pipelines:  add git retry with try/catch and retry(2)

jenkins/branch/autest.pipeline, jenkins/branch/clang_analyzer.pipeline, jenkins/branch/clang_format.pipeline, jenkins/branch/coverage.pipeline, jenkins/branch/in_tree.pipeline, jenkins/branch/os_build.pipeline, jenkins/branch/out_of_tree.pipeline, jenkins/branch/rat.pipeline
create new "branch" label for docker nodes and add that to the pipeline scripts
=> change label over to branch

jenkins/bin/build.sh
Added support for lsan and tsan in FEATURES field.
=> build.sh: add lsan/tsan support

jenkins/bin/build.sh, jenkins/bin/environment.sh
add asan env args to jenkins/bin/environment.sh
=> add asan env args

jenkins/bin/clang-analyzer.sh, jenkins/branch/clang_analyzer.pipeline
=> change clang_analylzer pipeline to use ubuntu:20.04

jenkins/branch/distro_builds.pipeline, jenkins/branch/os_build.pipeline
hopefully allows us to more easily identify asan/tsan/etc for builds.
=> add features to the display name

docker/centos/Dockerfile, docker/centos/build_h3_tools.sh
This also keeps around the h3 tools build directory for people to
reference later.
=> Updating the h3 tools pins

jenkins/bin/docs.sh, jenkins/branch/docs.pipeline
I should add a checkbox option to allow building without pushing the docs up.
=> Runs branch docs on the controller and writes directly to http docs

jenkins/branch/in_tree.pipeline
=> fix another pipeline typo

jenkins/branch/coverage.pipeline
This adds uniform logic for branch detection to coverage.pipeline
=> add branch detect code to coverage.pipeline

jenkins/branch/coverage.pipeline
It's in the ${WORKSPACE} already.
=> Remove ${GITHUB_BRANCH} from archive dir

jenkins/bin/docs.sh, jenkins/branch/docs.pipeline
Have 2 stages, each with their own dedicated node.  One for building docs on any branch machine and one for deploying on the controller.
=> docs branch build: split build and install hosts using stash/unstash

jenkins/branch/docs.pipeline
Changed from running docker agent on the controller to just having the controller do the install.
=> change from docker agent to just controller node

jenkins/github/ghprb-toplevel.pipeline, jenkins/github/toplevel.pipeline
We can't merge in PRs without CentOS running until we merge in
.asf.yaml.
=> Stop Gap: Run CentOS until .asf.yaml merged in.

jenkins/github/ghprb-toplevel.pipeline, jenkins/github/toplevel.pipeline
This reverts commit d9b9d41744c20f292375c77d7c2a917513c37141.
Pull in this revert when Evan's .asf.yaml change is merged in:
https://github.com/apache/trafficserver/pull/8679
=> Revert "Stop Gap: Run CentOS until .asf.yaml merged in. (#74)"

docker/rockylinux8/Dockerfile, jenkins/branch/autest.pipeline, jenkins/branch/coverage.pipeline, jenkins/github/autest.pipeline, jenkins/github/rocky.pipeline
Updating the rockylinux:8 compiler to gcc-toolset-11
=> Switch rockylinux to build with gcc-toolset-11

jenkins/fedora.pipeline, jenkins/github/fedora.pipeline
SHELL didn't work. Maybe CONFIG_SHELL will.
=> CONFIG_SHELL=/bin/bash

jenkins/branch/cache-tests.pipeline
just ended up chown -R 1200:1200 the workspace area, run test as root in the container.
=> more permissions changes

jenkins/github/fedora.pipeline
This will attempt to run autoreconf in a loop to see whether that helps
make it more stable.
=> Put fedora autoreconf in a loop

jenkins/bin/environment.sh
=> environment: set CONFIG_SHELL to /bin/bash and M4 to /bin/m4 if found

docker/alma/Dockerfile, docker/centos7/Dockerfile, docker/centos8/Dockerfile, docker/docs/Dockerfile, docker/fedora32/Dockerfile, docker/fedora35/Dockerfile, docker/fedora36/Dockerfile, docker/rockylinux8/Dockerfile
I noticed that an upgraded pip had fixes for M1. Updating it in our
Dockerfiles before use.
=> Upgrade pip before each use in each Dockerfile

docker/rockylinux8/Dockerfile
Fixes ATS issue:
https://github.com/apache/trafficserver/issues/8836
=> Rocky Linux 8: Use h2spec 2.6.0

jenkins/branch/autest.pipeline, jenkins/branch/branch_build.pipeline, jenkins/branch/distro_builds.pipeline
Adds support for autest sharding, defaults to 4 shards.
Also should fix branch branch build detection folder.
=> autest shard support through AUTEST_SHARD environment

jenkins/branch/distro_builds.pipeline
missed change for the autests_shard checkin
=> use correct api for popping back element

jenkins/branch/branch_build.pipeline
fix for branch build building the same thing over and over.
=> add def inside for loop for closure building

jenkins/bin/clang-analyzer.sh
=> remove head -1 README

jenkins/branch/autest.pipeline
restore the ||true to the autest pipeline job (testing).
=> restore or true

jenkins/github/rocky.pipeline
throwing this in to see how long it makes rocky builds
=> Add  --with-expensive-tests to rocky build alone

docker/rockylinux8/Dockerfile
* Use /etc/profile.d/go.sh
* Install the latest go (1.20.1.1).
=> Fix go and go application installation

jenkins/github/cmake.pipeline
This adds a pipeline script for PR CI builds to compile ATS with cmake.
=> Adding a cmake.pipeline for PR builds

docker/fedora38/Dockerfile, docker/fedora38/build_h3_tools.sh
fedora:38 won't be released until mid April, but might as well start this now while I'm testing with it in preparation for the release.
=> Start fedora:38 Dockerfile

jenkins/bin/cmake.sh, jenkins/branch/branch_build.pipeline, jenkins/branch/cmake.pipeline
Checks in the branch for a buildable cmake pipeline
=> add cmake pipeline for branch builds

docker/fedora38/Dockerfile, docker/fedora38/build_h3_tools.sh, docker/rockylinux8/Dockerfile, docker/rockylinux8/build_h3_tools.sh
Since the new build_h3_tools.sh installs quiche/boring, we no longer need to do this in the Dockerfiles.
=> Update and use the newer build_h3_tools.sh

jenkins/bin/github.sh, jenkins/bin/regression.sh, jenkins/branch/coverage.pipeline, jenkins/branch/quiche.pipeline, jenkins/github/centos.pipeline, jenkins/github/debian.pipeline, jenkins/github/fedora.pipeline, jenkins/github/rocky.pipeline, jenkins/github/ubuntu.pipeline
Use the -R 3 superset of regression tests rather than -R 1.
=> Regression tests: use -R 3

jenkins/bin/github.sh, jenkins/bin/regression.sh, jenkins/branch/coverage.pipeline, jenkins/branch/quiche.pipeline, jenkins/github/centos.pipeline, jenkins/github/debian.pipeline, jenkins/github/fedora.pipeline, jenkins/github/rocky.pipeline, jenkins/github/ubuntu.pipeline
The regression tests -R 3 seem to not run reliably in CI. So I'm
reverting this for now.
This reverts commit 5125dc35983be96992ca1ce7a6484349468670b6.
=> Revert "Regression tests: use -R 3 (#156)"

docker/rockylinux8/Dockerfile
Chris McFarlen could use this for the cmake work he's doing.
=> Install a recent cmake in rockylinux:8

docker/centos7/Dockerfile, docker/centos7/build_h3_tools.sh, jenkins/github/centos.pipeline, jenkins/github/fedora.pipeline
* CI centos:7 updates
* Have centos build with gcc-8
* Have fedora build with -std=20
=> Various summit updates

jenkins/bin/cmake.sh, jenkins/github/cmake.pipeline
Chris McFarlen pulled in some unit tests under ctest. We should run the target to make sure PRs don't break those.
=> Run ctest now that support has been added for it

jenkins/github/cmake.pipeline
Per Josiah's recommendation here:
https://github.com/apache/trafficserver/pull/9933
=> cmake: add debug build, use fedora:38

docker/fedora38/build_h3_tools.sh
In addition to updating the branch, we have to update the commit it checks out.
=> Updating the OpenSSL 3.0 commit

docker/fedora38/build_h3_tools.sh
On some systems, such as amd64 Linux, OpenSSL 3.0 installs into a lib64 directory instead of lib. This updates the build_h3_tools for this.
=> fedora38 build_h3_tools: update for lib64

jenkins/bin/cmake.sh, jenkins/github/cmake.pipeline
Now that this option is added, we might as well add it to our builds.
=> cmake: -DBUILD_EXPERIMENTAL_PLUGINS=ON

docker/debian/Dockerfile
Converts docker/debian/Dockerfile to build a debian 12 distro.
Also an example of 'here document' syntax in the Dockerfile
=> debian dockerfile to debian 12

jenkins/github/ubuntu.pipeline
Requires https://github.com/apache/trafficserver-ci/pull/215.
=> Use LLVM toolchain on ubuntu pipeline

jenkins/bin/cmake.sh
Updates cmake build from github cmake build
=> update cmake build, add quiche build

jenkins/github/autest.pipeline
This updates our PR autest CI to build with cmake, if it is available (i.e., the branch has the implementation for it).
=> PR Github AuTest CI: build with cmake

jenkins/github/centos.pipeline
=> Tweaks for centos cmake builds

docker/debian/Dockerfile, docker/rockylinux8/Dockerfile, docker/ubuntu2304/Dockerfile, jenkins/github/debian.pipeline, jenkins/github/ubuntu.pipeline
This should fix some cmake builds.
=> cmake Dockerfile updates

jenkins/github/debian.pipeline, jenkins/github/freebsd.pipeline, jenkins/github/rat.pipeline
I guess false isn't a shell thing. Using 1 -eq 0 instead.
=> Fix my false shortcircuits

jenkins/github/freebsd.pipeline
Evan helped me install cmake on the freebsd boxes, so we should be able to do cmake builds on them now.
=> cmake: update freebsd builds to use cmake

jenkins/github/freebsd.pipeline
Hopefully the resolv issue is addressed to the satisfaction of freebsd: https://github.com/apache/trafficserver/issues/10620
Putting this back in to try it out.
=> cmake: try freebsd again

jenkins/github/fedora.pipeline, jenkins/github/ubuntu.pipeline
Get rid of the ugly sed and use -DCMAKE_CXX_STANDARD=20 now that it is supported.
=> Us -DCMAKE_CXX_STANDARD=20 to set c++20

docker/ubuntu2204/Dockerfile, docker/ubuntu2304/Dockerfile
Also fix up the dockerfiles for 22.04 and 23.04
=> cmake for ubuntu 22.04

docker/ubuntu2204/Dockerfile, docker/ubuntu2304/Dockerfile
This will fix some CI test run permissions issues.
=> Adding the jenkins user to some ubuntu images

jenkins/github/ubuntu.pipeline
We decided this is what we'll support.
=> pr builds: use ubuntu:20.04 with clang-12

jenkins/bin/in_tree.sh, jenkins/bin/out_of_tree.sh, jenkins/branch/CMakePresets.json, jenkins/branch/coverity.pipeline
also disable in tree/out of tree for cmake
=> add coverity preset

jenkins/bin/cmake.sh, jenkins/branch/CMakePresets.json, jenkins/branch/os_build.pipeline
restore it to /tmp/ats, issues with locking
=> change branch build install loc

jenkins/bin/autotools.sh, jenkins/bin/cmake.sh, jenkins/bin/regression.sh, jenkins/branch/os_build.pipeline
=> fix regression.sh script

jenkins/bin/quiche.sh, jenkins/branch/quiche.pipeline
brings back quiche specific build and test.  autests to come.
=> restore branch quiche build

jenkins/github/centos.pipeline, jenkins/github/debian.pipeline, jenkins/github/docs.pipeline, jenkins/github/fedora.pipeline, jenkins/github/freebsd.pipeline, jenkins/github/osx.pipeline
Using updates from:
https://github.com/apache/trafficserver/pull/10779
=> Use updated cmake presets

jenkins/github/osx.pipeline
This is needed for the regression tests.
=> Have osx.pipeline install ats

jenkins/github/autest.pipeline
Otherewise, if there is other content in there, multiple PRs will get archived.
=> Limit archiveArtifacts to the PR number directory

docker/centos7/Dockerfile, docker/debian12/Dockerfile, docker/fedora39/Dockerfile, docker/rockylinux8/Dockerfile, docker/ubuntu2004/Dockerfile, docker/ubuntu2204/Dockerfile, docker/ubuntu2304/Dockerfile
These are for the uri_signing and stek_share plugins.
=> Adding cjose and nuraft

jenkins/branch/CMakePresets.json
=> branch builds to generate makefiles by default for compatibility

jenkins/branch/coverage.pipeline, jenkins/branch/coverity.pipeline
fix for coverity and coverage pipeline presets
=> fix pipelines for branch- prefix

jenkins/branch/CMakePresets.json, jenkins/branch/autest.pipeline, jenkins/branch/coverage.pipeline, jenkins/branch/coverity.pipeline, jenkins/branch/freebsd.pipeline, jenkins/branch/osx-m1.pipeline, jenkins/branch/osx.pipeline
Add cmake presets for freebsd, osx, osx-m1 and switch other pipelines to using branch- presets.
=> Branch pipelines other

jenkins/branch/CMakePresets.json
oops changed main asan instead of branch one
=> change correct preset asan for branch

jenkins/bin/clang-analyzer.sh
probably forgotten on accident, build in parallel for clang analyzer
=> add back in parallel cmake for clang-analyzer

jenkins/bin/autest.sh, jenkins/bin/autotools.sh, jenkins/bin/cache-tests.sh, jenkins/bin/clang-analyzer.sh, jenkins/bin/cleanup.sh, jenkins/bin/cmake.sh, jenkins/bin/cmake_basic.sh, jenkins/bin/coverity.sh, jenkins/bin/docs.sh, jenkins/bin/environment.sh, jenkins/bin/extract.sh, jenkins/bin/format.sh, jenkins/bin/gh-mirror.sh, jenkins/bin/github.sh, jenkins/bin/in_tree.sh, jenkins/bin/out_of_tree.sh, jenkins/bin/quiche.sh, jenkins/bin/rat.sh, jenkins/bin/regression.sh, jenkins/bin/snapshot.sh
this ensures scripts use bash and also uses a more cross platform NPROC
=> ensure shell scripts invoke bash

docker/centos7/build_h3_tools.sh
gmake[2]: Leaving directory '/root/build_h3_tools/nghttp2/third-party' Making all in src
gmake[2]: Entering directory '/root/build_h3_tools/nghttp2/src' Makefile:1237: ../tests/munit/.deps/nghttpx_unittest-munit.Po: No such file or directory gmake[2]: *** No rule to make target '../tests/munit/.deps/nghttpx_unittest-munit.Po'.  Stop. gmake[2]: Leaving directory '/root/build_h3_tools/nghttp2/src' gmake[1]: *** [Makefile:559: all-recursive] Error 1 gmake[1]: Leaving directory '/root/build_h3_tools/nghttp2' gmake: *** [Makefile:467: all] Error 2
I believe this is due to the test files being .c instead of .cc, and the older automake doesn't handle that well. This all worked on rockylinux:8, 9, and fedora:39. Giving up, at least for now. I wish there were a switch to turn off the unit tests.
=> I cannot get the nghttp2 to work on centos:7

docker/fedora40/Dockerfile, docker/fedora40/build_h3_tools.sh
Cleaning up fedora:38 while I'm at it.
=> Adding a fedora:40 Dockerfile

docker/rockylinux8/Dockerfile, docker/rockylinux8/build_boringssl_h3_tools.sh, docker/rockylinux8/build_openssl_h3_tools.sh
Build both openssl and boringssl quiche dependencies.
=> rockylinux:8 - quiche with openssl build tools

jenkins/bin/quiche.sh
=> branch-quiche -> branch-quiche-boringssl

jenkins/github/github_polling.pipeline
This is supposed to add the ability to do
[approve ci autest 1]
to rerun shard 1
if provided shard is less than zero or greater than number of shards nothing happens.
=> add the ability to only run single autest shards

jenkins/github/github_polling.pipeline, jenkins/github/toplevel.pipeline
It helps to add the code to the correct pipeline.
=> add autest shard extraction to correct pipeline

jenkins/github/toplevel.pipeline
Forgot to move the parallel job invocation into the shard run scope
=> move autest parallel job run into the parallel job scope

docker/rockylinux8/Dockerfile, docker/rockylinux8/build_boringssl_h3_tools.sh, jenkins/github/docs.pipeline
Also updates go for the required go packages.
=> rockylinux:8 - add python3.12 for Sphinx 8.*

jenkins/github/docs.pipeline
The previous commit set this as the default. Trying without this hard-coding in the script.
=> I think this hard-coding isn't needed anymore
