- docker/centos/Dockerfile
- docker/centos/build_h3_tools.sh
This builds openssl-quic and the corresponding HTTP/3 tools into the ATS
centos:8 Docker image. To do this, the centos Dockerfile runs a slightly
modified version of tools/build_h3_tools.sh from the
apache/trafficserver.git repo.
This also modifies /etc/profile to prepend /opt/bin to the PATH for
users so that the built version of curl with --http3 support is used for
the AuTests.
> Add openssl-quic to our centos:8 image.

- docker/centos/Dockerfile
- docker/centos/build_h3_tools.sh
- jenkins/branch/autest.pipeline
We face frequent permissions problems with running our AuTests as the
root user. Files get created as root, then the running ATS process,
running as user nobody, cannot access these files. This change adds a
jenkins user with the same uid that our jenkins machines have (uid
1200). This helps the tests run more smoothly.
> Adding and using a jenkins user with uid 1200

- jenkins/branch/autest.pipeline
This updates the PATH variable for the AuTest build and test run so that
it runs with /opt/bin/curl which is built with openssl-quic support.
> PATH updates to pick up openssl-quic curl.

- jenkins/branch/in_tree.pipeline
added an extra cleanWs() call to in_tree.pipeline, this removes that.
> remove extra cleanWs call

- jenkins/bin/environment.sh
This changes redhat/yum based builds to use devtoolset-9 instead of devtoolset-7
> environment from devtoolset-7 to devtoolset-9

- jenkins/branch/autest.pipeline
archiveArtifacts does not deal well with sockets. Exclude them from the
archived sandbox when there is a test failure.
> autest.pipeline: make archive exclude sockets

- jenkins/bin/clang-analyzer.sh
this is the current default in the old ci.
> disable running clang-analyzer for 8.1.x branch for now

- jenkins/branch/os_build.pipeline
Change how registry image name is built for the OS image.  Broken by a plugin update.
> change syntax for specifying docker image

- jenkins/github/fedora.pipeline
See:
https://github.com/apache/trafficserver/issues/8682
> Use fedora:32 until gcc-12 warnings are fixed

- jenkins/github/fedora.pipeline
This will compilation and linking with gcc-12.0.1.
> fedora.pipeline: fedora:32 -> fedora 36

- jenkins/github/fedora.pipeline
fedora:36 has openssl-3.x by default. ATS doesn't support that yet. For
now use the 1.1.1m that we build into our fedora:36 image.
> Use /opt/openssl-quic for fedora:36

- jenkins/github/fedora.pipeline
We're seeing frequent autoreconf failures with fedora:36. Hopefully
that's just because fedora:36 is currently beta. Switching to fedora:35.
> Use fedora:35 for PR checks

- jenkins/github/fedora.pipeline
There was an issue running autoreconf when we tried this last time. I've
tried reproducing this by hand on my mac and on docker21, but it worked
both times there. Putting this back to see how common this error is.
> Trying fedora:35 again.

- docker/cache-tests/Dockerfile
- docker/cache-tests/README.md
- jenkins/branch/autest.pipeline
- jenkins/branch/cache-tests.pipeline
- jenkins/branch/clang_analyzer.pipeline
- jenkins/branch/clang_format.pipeline
- jenkins/branch/coverage.pipeline
- jenkins/branch/docs.pipeline
- jenkins/branch/in_tree.pipeline
- jenkins/branch/os_build.pipeline
- jenkins/branch/out_of_tree.pipeline
- jenkins/branch/rat.pipeline
- jenkins/fedora.pipeline
- jenkins/github/autest.pipeline
- jenkins/github/centos.pipeline
- jenkins/github/clang-analyzer.pipeline
- jenkins/github/clang-format-test.pipeline
- jenkins/github/clang-format.pipeline
- jenkins/github/debian.pipeline
- jenkins/github/docs.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/rat.pipeline
- jenkins/github/rocky.pipeline
- jenkins/github/ubuntu-clang.pipeline
- jenkins/github/ubuntu.pipeline
- jenkins/ubuntu-param.pipeline
- jenkins/ubuntu.pipeline
ci.trafficserver.apache.org is the correct URL to use and it has the
correct externally facing cert as served by our controller's ATS. This
updates our scripts to use the ci.trafficserver.apache.org URL so that
people copying the image name from jenkins console output will be able
to use that locally if they so desire.
> controller.trafficserver.org -> ci.trafficserver.apache.org

- jenkins/github/fedora.pipeline
Applying what we did for branch builds to the fedora github CI builds:
38a1eb4e87d4ff8c9feb6c81d72ce2addc83fbc2
> M4=/bin/m4 for fedora:35 autoreconf github builds

- jenkins/github/fedora.pipeline
More attempts at helping the fedora builds.
> fedora: Explicitly put /bin in PATH; export M4/CONFIG_SHELL

- jenkins/bin/environment.sh
- jenkins/bin/in_tree.sh
- jenkins/bin/out_of_tree.sh
- jenkins/bin/rat.sh
- jenkins/bin/regression.sh
- jenkins/branch/clang_format.pipeline
- jenkins/branch/docs.pipeline
- jenkins/branch/in_tree.pipeline
- jenkins/branch/os_build.pipeline
- jenkins/branch/out_of_tree.pipeline
- jenkins/branch/rat.pipeline
This adds more set -x calls so we can have greater visibility into what
commands are being run in CI when there is a failure.
> Add more 'set -x'

- jenkins/github/fedora.pipeline
This updates the github PR fedora build to use fedora:36.
I did an ATS master build with this locally and it all built. Updating CI to check this with each PR so it stays working.
> fedora:36 is officially released. Use it in CI.

- jenkins/bin/docs.sh
- jenkins/github/docs.pipeline
Exception for 8.1.x for both branch and github doc builds.
> Enable strict docs generation for branch builds, exception for 8.1.x

- jenkins/github/autest.pipeline
- jenkins/github/toplevel.pipeline
This modifies toplevel and autest pipelines to shard the autests.  Set in toplevel pipeline configuration to '5' currently.
On the github PR page, now where will be multiple Autest Checks instead of the single one
- AuTest 0of5
- AuTest 1of5
- AuTest 2of5
- ...
Additionally on the Jensking Github_PR_Checks page will have corresponding names to the above.
Note sample at:
https://github.com/traeak/trafficserver/pull/1
when comparing files please add ?w=1 to ignore white space.
> add autest sharding to pr builds

- docker/rockylinux8/Dockerfile
This builds and installs quich in /opt/quiche so we can test building ATS using quiche.
> Add dependencies for building ATS with quiche

- jenkins/github/autest.pipeline
- jenkins/github/centos.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/rocky.pipeline
Some scripts still --enable-luajit...I didn't remove it from the branch pipelines in case it was still helpful there, and some shell scripts still reference it in case that's helpful for the same reason.
> Removing call to --enable-luajit in jenkins jobs

- docker/rockylinux8/Dockerfile
Python's httpbin is unsupported and depends upon an old werkzeug package.
> Install go-httpbin to replace pip httpbin for autests

- jenkins/github/rocky.pipeline
The real change here, other than whitespace, is:
`--with-openssl=/opt/openssl-quic` -> `--with-quiche=/opt/quiche`
> Change Rocky build to use the quiche build

- jenkins/github/osx.pipeline
This way we'll catch patches that introduce osx warnings.
> osx PR builds: add --enable-werror

- jenkins/branch/quiche.pipeline
I initially configured the quiche branch job to use `-R 3` for the
regression tests while all other jenkins scripts use `-R 1`. I thought
we might fix the `-R 3` but that hasn't happened yet. The issue is
recorded here:
https://github.com/apache/trafficserver/issues/9576
Once that is fixed, we should update some CI jobs to use `-R 3` again.
In the meantime, we should make the quiche branch job use `-R 1` to
match the other jobs and catch if something breaks the quiche builds.
> Make quiche regression tests use -R 1

- docker/fedora38/Dockerfile
Presumably the stock pip is fine, but trying to upgrade breaks (at least currently).
> pip3 install --upgrade pip not working in fedora:38

- docker/rockylinux8/Dockerfile
This has a fix for /bytes/0 to actually return 0 bytes.
> Update to go-httpbin v2.6.0

- jenkins/branch/autest.pipeline
- jenkins/branch/coverage.pipeline
- jenkins/branch/quiche.pipeline
- jenkins/github/autest.pipeline
Ensure that the pipelines running autest.sh have /usr/local/go/bin in their PATH so it can find go-httpbin and h2spec.
> Ensuring /usr/local/go/bin in PATH for autests

- jenkins/branch/quiche.pipeline
- jenkins/github/rocky.pipeline
This is needed for now because the quiche rpath doesn't contain an update for the location of the boringssl location. This should fix some issues with quiche builds.
> /opt/boringssl/lib64 to LD_LIBRARY_PATH

- jenkins/github/centos.pipeline
The old git in centos:7 doesn't recognize --no-patch
> For old git in centos:7: --no-patch -> -s

- docker/centos7/Dockerfile
- docker/fedora38/Dockerfile
- docker/rockylinux8/Dockerfile
- docker/rockylinux9/Dockerfile
This takes up a lot of space, especially now that boring is in there.
This cuts the rockylinux:8 build down to 3.5 GB from 7.5 GB.
> Remove the build_h3_tools dir

- jenkins/github/fedora.pipeline
We now support openssl 3.x. We might as well test it with our PR builds. fedora:38 ships with openssl 3.x, so converting that to use the system ssl.
> Have fedora builds test with system openssl 3.x

- jenkins/github/ubuntu.pipeline
This updates the Ubuntu PR CI job to Ubuntu 23.04 and turns on c++20 for it. Since this jobs runs with clang, this gives us recent clang builds with the C++20 flag turned on.
> Update CI PR Ubuntu to 23.04

- docker/fedora38/Dockerfile
- docker/rockylinux8/Dockerfile
Also, the system lcov is 1.15, so I think installing from yum should be fine.
This applies the same changes from rockylinux (use heredocs) to fedora:38 Dockerfile:
https://github.com/apache/trafficserver-ci/pull/176
> fedora:38 Dockerfile to use heredoc

- jenkins/github/rat.pipeline
It turns out that we've been missing the libswoc license failures from
RAT because there are 30 failures, making the report contain this:
30 Unknown Licenses
Our grep currently sees the '0 Unknown Licenses' substring on this and
passes. This makes sure that the 0 is a leading zero at the start of the
line.
We must not merge this until some fix is made for the libswoc licenses
(either ignore them or update the libswoc licenses to be the more
verbose versions).
> Make the RAT license check pipeline more precise

- docker/fedora38/build_h3_tools.sh
- docker/rockylinux8/build_h3_tools.sh
In build_h3_tools, support Linux arm64 whose uname -m is aarch64. This is already in ATS tools/build_h3_tools.sh
> build_h3_tools: account for aarch64

- jenkins/github/autest.pipeline
This runs the autests on the newer fedora:38, which should help catch issues on the newest Python and other system packages. It should also help developers as they can reproduce CI issues locally on a recent OS and we support fedora:38 multiarchtecture for both linux/arm64 and linux/amd64.
> PR autest: run on fedora:38

- docker/fedora38/build_h3_tools.sh
This is what the apache/trafficserver/tools/build_h3_tools.sh file now uses.
> Update build_h3_tools for fedora:38 to Openssl 3.0

- docker/fedora38/build_h3_tools.sh
I don't know how I missed this in the previous commit.
> Fix another fedora:38 build_h3_tools openssl pkgconfig

- jenkins/github/debian.pipeline
Change from sunlit debian 10 to debian 12 for github pr builds.
> change to debian 12 for github pr builds

- jenkins/bin/cmake.sh
- jenkins/github/cmake.pipeline
Treat warnings as errors in CI.
> cmake: -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

- docker/rockylinux8/Dockerfile
Adding rockylinux:8 perl module install list for the latest build_h3_tools.sh.
> rockylinux:8 Dockerfile: add perl modules

- jenkins/branch/quiche.pipeline
- jenkins/github/rocky.pipeline
Now that Damian's rpath fix for https://github.com/cloudflare/quiche/pull/1508 has landed, we no longer need to explicitly set LD_LIBRARY_PATH for our quiche builds.
> Remove the setting of LD_LIBRARY_PATH for boring

- jenkins/bin/clang-analyzer.sh
- jenkins/branch/clang_analyzer.pipeline
This allows the DISTRO to be overridden.  Currently the pipeline has hard coded the latest and greatest distro set to ubuntu 22.04.
the clang-analyzer.sh will look for the scan-build executable via:
SCAN_BUILD=$(ls /usr/bin/scan-build* | grep -v py | tail -n 1)
> Enable old releases to use older clang-analyzer images

- docker/fedora39/Dockerfile
- docker/fedora39/build_h3_tools.sh
fedora:39 is in pre-beta so far, but might as well start the Dockerfile, create an early image, try it out, and update as time goes on. We probably won't use this in CI yet until we get closer to the release date in a couple months.
It's early enough that this Dockerfile fails with even a dnf update. Eventually the upstream fedora:39 should be stable enough for us to create images to test with.
> Starting fedora:39 images

- docker/rockylinux8/Dockerfile
We decided that we will support the system cmake for rockylinux:8, version 3.20. This reverts the manual update of cmake to the more recent 3.26 version to instead use the system 3.20 version so we test with that in CI.
> rockylinux:8 - use system cmake

- jenkins/github/rocky.pipeline
This affords us coverage of cmake 3.20 which we've committed to supporting for cmake.
> rocky:8 - Use cmake for PR CI jobs

- jenkins/github/rocky.pipeline
Our rockylinux:8 image doesn't have ninja, so revert to the default make system (Make).
> rocky ci: Use Make instead of ninja

- jenkins/github/rocky.pipeline
Fall back to rocky using automake until
https://github.com/apache/trafficserver/issues/10232 is fixed.
> Retreat rocky to use automake still

- docker/fedora39/Dockerfile
- docker/fedora39/build_h3_tools.sh
We won't use some of these differences long term, but at least it gets the build working so we can test with fedora:39.
> fedora:39 hacks to finish build the image

- jenkins/github/rocky.pipeline
This reverts commit db2e7b9eb294e937d398b2f74d68305d8752276c.
Chris fixed cmake 3.20 builds via:
https://github.com/apache/trafficserver/pull/10236
> Revert "Retreat rocky to use automake still (#207)"

- jenkins/github/clang-format.pipeline
lib/yamlcpp is a third party. Avoid whitespace checks for it.
> lib/yamlcpp: avoid trailing whitespace check

- docker/fedora38/Dockerfile
- docker/fedora39/Dockerfile
Looks like rockylinux:8 already includes pcre2-devel implicitly somehow.
> Add pcre2-devel to fedora

- docker/ubuntu2304/Dockerfile
The `ci.trafficserver.apache.org/ats/ubuntu:23.04` image doesn't have `lld` and using old GNU `ld` with llvm toolchain.
> Add lld to ubuntu2304 image

- jenkins/github/autest.pipeline
testsall has to be computed in the src/tests directory, not in the build directory. src/tests is where the gold tests live.
> Fix testsall computation

- jenkins/github/centos.pipeline
- jenkins/github/cmake.pipeline
- jenkins/github/debian.pipeline
- jenkins/github/docs.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/freebsd.pipeline
- jenkins/github/osx.pipeline
- jenkins/github/rat.pipeline
- jenkins/github/rocky.pipeline
- jenkins/github/ubuntu.pipeline
We'll still need a rat target and an -DENABLE_HARDENING=ON feature. But most of the PR builds can be done via cmake now.
> Convert as many PR builds to cmake as possible

- jenkins/github/autest.pipeline
- jenkins/github/centos.pipeline
- jenkins/github/clang-format.pipeline
- jenkins/github/cmake.pipeline
- jenkins/github/debian.pipeline
- jenkins/github/docs.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/freebsd.pipeline
- jenkins/github/osx.pipeline
- jenkins/github/rat.pipeline
- jenkins/github/rocky.pipeline
- jenkins/github/ubuntu.pipeline
Hopefully this fixes docs at least. It also makes the cmake detection more reliable than just looking at the branch and making sure it's not 9.x
> Some cmake updates.

- jenkins/github/freebsd.pipeline
We'll install cmake on freebsd shortly, but for now avoid cmake builds until that is done.
> freebsd: avoid cmake until it's installed in CI

- jenkins/github/freebsd.pipeline
Reverts apache/trafficserver-ci#237
Reverting until we get freebsd working pthread_create:
```
[ 25%] Linking CXX executable test_tscore
cd /usr/home/jenkins/workspace/Github_Builds/freebsd/src/cmake-build-release/src/tscore && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/test_tscore.dir/link.txt --verbose=1
/usr/bin/c++ CMakeFiles/test_tscore.dir/unit_tests/test_AcidPtr.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_ArgParser.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_CryptoHash.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_Errata.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_Extendible.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_Encoding.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_HKDF.cc.o CMakeFiles/test_tscore.dir/unit_tests/test_Histogram.cc.o …
```
> Revert "cmake: try freebsd again"

- jenkins/github/freebsd.pipeline
Evan just did this for osx.pipeline, applying it now to freebsd.pipeline. This way re-runs of freebsd.pipeline will always run with the latest rebase on top of the target branch.
> Update freebsd.pipeline to merge up to latest upstream

- jenkins/github/debian.pipeline
Switch debian to cmake since there is a preset which applies hardening flags.
> cmake: preset ci-debian now runs hardening.

- jenkins/github/freebsd.pipeline
cmcfarlen patched freebsd cmake builds for pthread. Let's see if the freebsd build is green now.
> freebsd: try cmake again

- jenkins/github/clang-analyzer.pipeline
Updating clang-analyzer.pipeline to use cmake for builds now.
> clang-analyzer: use cmake

- jenkins/github/clang-analyzer.pipeline
I accidentally grabbed the wrong cmake directory check in the previous commit.
> Fix the cmake check for clang-analyzer

- jenkins/github/centos.pipeline
Ninja builds automatically use all the available cores on a box, but Unix Makefiles builds don't. Add -j4 explicitly.
> centos: use -j4

- jenkins/github/clang-analyzer.pipeline
Supposedly ccache can confuse clang-analyzer. We never ran with ccache before, so avoid it here for cmake builds as well.
> disable ccache for clang-analyzer

- jenkins/bin/clang-analyzer.sh
- jenkins/bin/cmake.sh
- jenkins/bin/quiche.sh
- jenkins/branch/CMakePresets.json
This is prep work for adding 'branch' cmake presets into ATS master.
New cmake entries are prefixed 'branch-' and the generated cmake user preset is called 'branch-user-preset' which inherits from these 'branch-' entries.
> Cmake branch prefix

- jenkins/branch/freebsd.pipeline
- jenkins/branch/osx-m1.pipeline
- jenkins/branch/osx.pipeline
This ensures trafficserver-ci is available in osx/freebsd pipelines.
> osx/freebsd: check out trafficserver-ci

- docker/rockylinux9/Dockerfile
for rockylinux 9 docker container
> reinstall openssl-devel at the end for older branch builds

- jenkins/github/autest.pipeline
- jenkins/github/centos.pipeline
- jenkins/github/clang-analyzer.pipeline
- jenkins/github/debian.pipeline
- jenkins/github/docs.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/format.pipeline
- jenkins/github/freebsd.pipeline
- jenkins/github/osx.pipeline
- jenkins/github/rat.pipeline
- jenkins/github/rocky.pipeline
- jenkins/github/ubuntu.pipeline
In particular, the show of `HEAD^2` and `HEAD^1` should ensure that both parents of the merge commit are printed.
> Print some more information at the beginning

- jenkins/bin/cmake.sh
The read statement for using a block was returning '1' for some reason and blowing up with set -e
This replaces it with just setting the contents with an escaped multiline string.
> simplify setting json contents for CMakeUserPresets.json

- jenkins/github/rocky.pipeline
Now that yaml-cpp and libswoc are installed in /opt in the rocky images, use those install dirs instead of building each of these for each build.
> PR rocky: use /opt/yaml-cpp and /opt/libswoc

- docker/rockylinux8/build_h3_tools.sh
- docker/rockylinux9/build_h3_tools.sh
This failed for fedora:39, so not updating that.
> build_h3_tools updates for static boringssl

- jenkins/github/fedora.pipeline
The autest build has at least v6 resolution issues which I hope will get resolved as fedora hardens up and comes out of beta. But for now we can at least use the updated compiler from fedora:40
> fedora build to use 40

- docker/fedora39/Dockerfile
The proxy-wasm needs a WebAssembly runtime. This adds WAMR to satisfy this.
> Add WAMR for proxy-wasm

- jenkins/bin/regression.sh
Without the explicit `exit 1` the script finishes with an exit code of 8 which was maybe making it so the tests didn't fail. Maybe? In any case, this shouldn't hurt and may make the failure explicit in jenkins.
> regression.sh: ctest exit with 1 on failure

- docker/fedora40/Dockerfile
This brings our CI fedora:40 up to date with fedora:39
> fedora:40 - Add wamr for plugin wasm builds

- jenkins/github/autest.pipeline
This updates the autest github PR pipeline to use fedora:40
> github autest pipeline: use fedora:40

- docker/fedora40/Dockerfile
- docker/fedora40/build_boringssl_h3_tools.sh
- docker/fedora40/build_openssl_h3_tools.sh
Pull in the updated tools/build_h3_tools.sh work from ATS.
> fedora:40: build quiche with both openssl and boringssl

- jenkins/bin/quiche.sh
- jenkins/branch/quiche.pipeline
Support quiche built on top of openssl as well as boringssl.
> quiche branch builds: support openssl

- jenkins/github/autest.pipeline
We wish to add an autest for eBPF tracing.  Using eBPF tracing inside a docker container requires the container to be `--privileged`.  After kernel 5.8 there is CAP_BPF, but the VM that we run on has kernel 5.4.
> Add --privileged to github autest docker container

- jenkins/github/autest.pipeline
Running bpftrace in the docker is going to require root-level access in the container, which is problematic when the container is privileged.  Let's not run that autest in CI.
> Revert "Add --privileged to github autest docker container"

- jenkins/github/rocky.pipeline
For https://github.com/apache/trafficserver/pull/11332
> Set LSan suppression for regression test

- docker/fedora40/build_boringssl_h3_tools.sh
- docker/fedora40/build_openssl_h3_tools.sh
- docker/rockylinux8/build_boringssl_h3_tools.sh
- docker/rockylinux8/build_openssl_h3_tools.sh
build_h3_tools updates from master and:
https://github.com/apache/trafficserver/pull/11493
> fedora:40 rockylinux:8 build_h3_tools_updates

- docker/fedora41/Dockerfile
- docker/fedora41/build_boringssl_h3_tools.sh
- docker/fedora41/build_openssl_h3_tools.sh
Also cleans up the fedora:39 Dockerfile.
This is preperatory. Hopefully within the next few weeks we'll be able to create a fedora:41 ATS image. Official beta is tomorrow.
> fedora:41 Dockerfile

- docker/fedora41/Dockerfile
openssl-devel-engine is needed since the Engine API is removed in fedora:41 due to it being deprecated in OpenSSL 3.*. The following ATS issue tracks this problem:
https://github.com/apache/trafficserver/issues/7512
> fedora:41 Add openssl-devel-engine

- docker/rockylinux8/Dockerfile
- docker/rockylinux9/Dockerfile
We cannot merge ATS libswoc update until we update rocky. So explicitly set libswoc versions installed in rocky.
> Set libswoc version explicitly

- jenkins/github/docs.pipeline
Reverts apache/trafficserver-ci#372
Nevermind: it looks like this is needed lest Python3.6 (the rockylinux:8 system default) is used.
> Revert "I think this hard-coding isn't needed anymore"

- jenkins/bin/docs.sh
The latest Sphinx requires Python 3.12
> Use Python3.12 for branch docs builds

- jenkins/bin/cmake.sh
- jenkins/bin/cmake_basic.sh
- jenkins/bin/quiche.sh
- jenkins/bin/regression.sh
- jenkins/branch/coverage.pipeline
- jenkins/github/centos.pipeline
- jenkins/github/debian.pipeline
- jenkins/github/fedora.pipeline
- jenkins/github/osx.pipeline
- jenkins/github/rocky-asan.pipeline
- jenkins/github/rocky.pipeline
- jenkins/github/ubuntu.pipeline
Trying to remove the `-k` parameter caused problems with the CI builds
> remove -k to traffic_server for cmake builds
